
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
import Navbar from "../navbar/page";
import AppLayout from "./components/AppLayout";
import { Navigation } from "@/components/navigation";
import LayoutWrapper from "./layoutwrapper";
// import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const[issidebaropen,setissidebaropen] = useState(false);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* <Navbar/> */}
         {/* <Navigation/> */}
        {/* <AppLayout>   */}
       <LayoutWrapper> 
        {children}
        </LayoutWrapper>
        {/* </AppLayout> */}
        </body>
    </html>
    </ClerkProvider>
  );
}
